services:
  story-stream-frontend:
    image: ivanmonichev/story-stream-frontend:latest
    container_name: story-stream-frontend
    restart: always
    ports:
      - "3000:8080"
    environment:
      VITE_API_URL: ${VITE_API_URL}
